my_store/config/routes.rb
MyStore::Application.routes.draw do
  get "users/new"

  get "users/create"

  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_out" => "sessions#destroy", :as => "sign_out"
  root :to => "home_pages#index"

  resources :users, :sessions, :products, :articles, :comments

  namespace :admin do
    resources :categories
  end
  
  match 'products/:category_id/find_by_category' => 'products#find_by_category', :as => :find_product_by_category
  
end

my_store/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, 
                  :description,
                  :price,
                  :weight,
                  :user_id,
                  :category_id

  belongs_to :user
  belongs_to :category
end

my_store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_login, :only=>[:new,:create]
  before_filter :find_by_id, :only=>[:edit,:update, :destroy]

  def index
    @products=Product.all
  end

  def new
    @product=Product.new
    @categories=Category.all.map{|x| [x.name, x.id]}
  end
  
  def create
    @product=Product.new(params[:product])
    @product.user_id=session[:user_id]
    if @product.save
      flash[:notice]='Product has been created'
      redirect_to products_path
    else
      flash[:error]='Cannot create new product'
      render "new"
    end
  end
  
  def show
    @product=Product.find(params[:id])
  end
  
  def find_by_category
  @products = Product.find_all_by_category_id(params[:category_id])
  render "index"
  end

  def edit
    @categories=Category.all.map{|x| [x.name, x.id]}
  end

  def update
    if @product.user_id == session[:user_id] || User.find(session[:user_id]).email == "admin@admin.com"
      if @product.update_attributes(params[:product])
        redirect_to products_path
      else
        flash[:error]='Cannot update product'
        render "edit"
      end
    else
      flash[:error]="You not permitted to update product"
      redirect_to products_path
    end
  end

  def destroy
    if @product.user_id == session[:user_id] || User.find(session[:user_id]).email == "admin@admin.com"
      if @product.destroy
        redirect_to products_path
      else
        flash[:error]='Cannot delete product'
        redirect_to products_path
      end
    else
      flash[:error]="You not permitted to delete product"
      redirect_to products_path
    end
  end

  private
  def find_by_id
    @product=Product.find(params[:id])
  end
end

my_store/app/helpers/products_helper.rb
module ProductsHelper
end

my_store/app/views/products/edit.html.erb
<header style="border-top: 1px solid #333;border-bottom: 1px solid #333; margin-bottom:10px">
  <h3>Update Product</h3>
</header>
<%= form_for @product, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="control-group">
    <label class="control-label" for="name">Name</label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="description">Description</label>
    <div class="controls">
      <%= f.text_area :description, :rows=>3 %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="price">Price</label>
    <div class="controls">
      <%= f.number_field :price %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="weight">Weight</label>
    <div class="controls">
      <%= f.text_field :weight %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="parent_category">Parent Category</label>
    <div class="controls">
      <%= f.select :category_id, @categories, { :include_blank => true } %>
    </div>
  </div>
  <%=f.submit :update%> <%=link_to "Back", products_path %>
<%end%>

my_store/app/views/products/index.html.erb
<header style="border-top: 1px solid #333;border-bottom: 1px solid #333;margin-bottom:10px">
  <h3>Listing Product</h3>
</header>
<section>
  <%@products.each do|product|%>
  <div class="product-block" id=<%=product.id%> style="border: 1px solid;padding: 3px;width: 200px;float: left;">
    <span>Name: <%=product.name%></span><br />
    <span>Price: <%=product.price%></span><br />
    <span>
      <%=link_to "See More", product_path(product.id)%> |
      <% if product.user_id == session[:user_id] || User.find(session[:user_id]).email=="admin@admin.com" %>
        <%=link_to "Edit", edit_product_path(product.id)%> | <%=link_to "delete", product_path(product.id), :method=>"delete", :confirm=> "Are you sure?"%>
      <%end%>
    </span>
  </div>
  <%end%>
</section>

my_store/app/views/products/new.html.erb
<header style="border-top: 1px solid #333;border-bottom: 1px solid #333; margin-bottom:10px">
  <h3>Create New Product</h3>
</header>
<%= form_for @product, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="control-group">
    <label class="control-label" for="name">Name</label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="description">Description</label>
    <div class="controls">
      <%= f.text_area :description, :rows=>3 %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="price">Price</label>
    <div class="controls">
      <%= f.number_field :price %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="weight">Weight</label>
    <div class="controls">
      <%= f.text_field :weight %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="parent_category">Parent Category</label>
    <div class="controls">
      <%= f.select :category_id, @categories, { :include_blank => true } %>
    </div>
  </div>
  <%=f.submit :create%> <%=link_to "Back", products_path %>
<%end%>

my_store/app/views/products/show.html.erb
<header>
  <h3>Detail Product</h3>
</header>
<section>
  <dl>
    <dt>Name</dt>
    <dd><%=@product.name%></dd>
    <dt>Description</dt>
    <dd><%=@product.description%></dd>
    <dt>Price</dt>
    <dd><%=@product.price%></dd>
    <dt>Weight</dt>
    <dd><%=@product.weight%></dd>
  </dl>
</section>

<%=link_to "Back to products list", products_path%>