my_store/config/routes.rb
MyStore::Application.routes.draw do
  get "users/new"

  get "users/create"

  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_out" => "sessions#destroy", :as => "sign_out"
  root :to => "home_pages#index"

  resources :users, :sessions, :products, :articles, :comments

  namespace :admin do
    resources :categories
  end
  
  match 'products/:category_id/find_by_category' => 'products#find_by_category', :as => :find_product_by_category
  
end

my_store/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, 
                  :body,
                  :user_id

  belongs_to :user
  has_many :comments
end

my_store/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_admin_login, :only=>[:new,:create]
  def index
    @articles=Article.all
  end
  
  def new
    @article=Article.new
  end

  def create
    @article=Article.new(params[:article])
    @article.user_id=session[:user_id]
    if @article.save
      redirect_to articles_path
    else
      flash[:error]="cannot create new article"
      render "new"
    end
  end

  def show
    @article=Article.find(params[:id])
    @comments=@article.comments
    @comment=Comment.new
  end
  
end

my_store/app/helpers/articles_helper.rb
module ArticlesHelper
end

my_store/app/views/articles/index.html.erb
<header style="border-top: 1px solid #333;border-bottom: 1px solid #333;margin-bottom:10px">
  <h3>Lates Article</h3>
</header>
<section>
  <%@articles.each do|article|%>
  <div class="article-block" id=<%=article.id%> style="border-bottom: 1px solid;padding: 3px;">
    <span>Title: <%=article.title%></span><br />
    <span>Body: <%=article.body%></span><br />
    <span>
      <%=link_to "See More", article_path(article.id)%>
    </span>
  </div>
  <%end%>
</section>

my_store/app/views/articles/new.html.erb
<header style="border-top: 1px solid #333;border-bottom: 1px solid #333; margin-bottom:10px">
  <h3>New Article</h3>
</header>
<%= form_for @article, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="control-group">
    <label class="control-label" for="name">Name</label>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="description">Description</label>
    <div class="controls">
      <%= f.text_area :body, :rows=>3 %>
    </div>
  </div>
  <%=f.submit :create%> <%=link_to "Back", articles_path %>
<%end%>

my_store/app/views/articles/show.html.erb
<section class="article-container">
  <p>
    <h3><%=@article.title%></h3>
  </p>
  <p>
    <%=@article.body%>
  </p>
</section>

<label>Comments:</label>
<div id="comments" style="margin-bottom:15px">
  <table class="table table-striped">
    <%if @comments.length != 0%>
      <%=render :partial=>"shared/comments", :locals => {:comments => @comments}%>
    <%else%>
      <tr>
        <td>
          No Comments Yet
        </td>
      </tr>
    <% end %>
  </table>
</div>


<%=form_for @comment, :url => comments_path, :remote => true, :html => {:class => "form"} do |f|%>
  <div class="control-group">
    <div class="controls">
      <%=f.text_area :comment, :rows=>3 %>
      <%= f.hidden_field :article_id, :value => @article.id %>
      <%= f.hidden_field :user_id, :value => session[:user_id] %>
    </div>
  </div>
  <%=f.submit :create%>
<%end%>